### ISSUE TITLE
lybniz fails to build and install 

### ISSUE THREAD

**Issue by drew-parsons** [thomasfuhringer/lybniz#9]
lybniz 3.0.4 now fails to build and install. The error message (running clean) is
```
$python3.11 setup.py clean 
error: Multiple top-level packages discovered in a flat-layout: ['po', 'images', 'locale', 'Archive'].

To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this build.

If you are trying to create a single distribution with multiple packages
on purpose, you should not rely on automatic discovery.
Instead, consider the following options:

1. set up custom discovery (`find` directive with `include` or `exclude`)
2. use a `src-layout`
3. explicitly set `py_modules` or `packages` with a list of names

To find more information, look for "package discovery" on setuptools docs.
```

This is with python 3.11.6 and setuptools 68.1.2 (on debian unstable).

I think the problem probably comes from the new version of setuptools.  Many projects have been moving their package install script from setup.py to pyproject.toml, documented at https://packaging.python.org/en/latest/tutorials/packaging-projects/

**Comment by drew-parsons** [comment]
Since lybniz doesn't provide a python package as such, only the executable identified in the scripts entry, it's enough to simply add an empty packages entry in the setup rule
```
Index: lybniz/setup.py
===================================================================
--- lybniz.orig/setup.py	2023-11-24 22:18:48.522755773 +0100
+++ lybniz/setup.py	2023-11-24 22:34:12.659223545 +0100
@@ -24,6 +24,7 @@
 	contact = 'Thomas Führinger',
 	contact_email = 'ThomasFuhringer@Yahoo.com',
 	url = 'github.com/thomasfuhringer/lybniz',
+	packages = [],
 	scripts = ['lybniz'],
 	data_files = data_files,
 	license = 'BSD',

```

**Comment by thomasfuhringer** [comment]
Thanks Drew,
I added the line as you suggested.

I did not personally make this setup file so I am not actually familiar with it. Hope this helps.
- Thomas

**Comment by drew-parsons** [comment]
Looks good.  We can close this issue with that patch.
